fix(ci): rewrite ci script to match current project

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -7,67 +7,66 @@ on:
     branches: [ main ]
 
 jobs:
-#  checking-code-format:
-#    name: check code format with clang-format
-#    runs-on: ubuntu-22.04
-#    strategy:
-#      matrix:
-#        path:
-#          - check: 'module'
-#            exclude: '(stelaLowparser|stelaLowscanner|lowparser|lowscanner)'
-#    steps:
-#    - name: checkout repository codes
-#      uses: actions/checkout@v4
-#      with:
-#        fetch-depth: 0
-#
-#    - name: cache APT packages
-#      uses: actions/cache@v4
-#      with:
-#        path: /var/cache/apt
-#        key: ${{ runner.os }}-apt-${{ hashFiles('/var/lib/apt/lists/lock') }}
-#        restore-keys: |
-#          ${{ runner.os }}-apt-
-#
-#    - name: cache Docker packages
-#      uses: actions/cache@v4
-#      with:
-#        path: |
-#          /var/cache/apt/archives
-#          /etc/apt/keyrings/docker.asc
-#        key: ${{ runner.os }}-docker-packages
-#        restore-keys: |
-#          ${{ runner.os }}-docker-
-#
-#    - name: install native dependencies
-#      run: |
-#        sudo apt update
-#        sudo apt-get install ca-certificates curl
-#        sudo install -m 0755 -d /etc/apt/keyrings
-#        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-#        sudo chmod a+r /etc/apt/keyrings/docker.asc
-#
-#        echo \
-#          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
-#          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
-#          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-#        sudo apt-get update
-#        
-#        sudo apt-get install python3 docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-#
-#    - name: run formatter 
-#      run: |
-#        cd ${{github.workspace}} 
-#        python3 build/builder.py format docker
-#
-#    - name: check if there is a style violiations 
-#      run: |
-#        git diff > output.txt
-#        if [ -s output.txt ]; then
-#          echo "error: some codes violates our code style."
-#          cat output.txt
-#          exit 1
-#        fi
+  checking-code-format:
+    name: check code format with clang-format
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        path:
+          - check: 'module'
+    steps:
+    - name: checkout repository codes
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: cache APT packages
+      uses: actions/cache@v4
+      with:
+        path: /var/cache/apt
+        key: ${{ runner.os }}-apt-${{ hashFiles('/var/lib/apt/lists/lock') }}
+        restore-keys: |
+          ${{ runner.os }}-apt-
+
+    - name: cache Docker packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          /var/cache/apt/archives
+          /etc/apt/keyrings/docker.asc
+        key: ${{ runner.os }}-docker-packages
+        restore-keys: |
+          ${{ runner.os }}-docker-
+
+    - name: install native dependencies
+      run: |
+        sudo apt update
+        sudo apt-get install ca-certificates curl
+        sudo install -m 0755 -d /etc/apt/keyrings
+        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+        sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+        echo \
+          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
+          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+        sudo apt-get update
+        
+        sudo apt-get install python3 docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+
+    - name: run formatter 
+      run: |
+        cd ${{github.workspace}} 
+        python3 build/builder.py format docker
+
+    - name: check if there is a style violiations 
+      run: |
+        git diff > output.txt
+        if [ -s output.txt ]; then
+          echo "error: some codes violates our code style."
+          cat output.txt
+          exit 1
+        fi
 
   build-on-linux-clang:
     name: build on linux with clang
@@ -76,24 +75,6 @@ jobs:
     steps:
     - name: checkout repository codes
       uses: actions/checkout@v4
-
-    - name: cache Bison source
-      uses: actions/cache@v4
-      id: bison-source-cache
-      with:
-        path: bison-3.8.2.tar.gz
-        key: bison-source-3.8.2
-
-    - name: cache Bison binary
-      uses: actions/cache@v4
-      id: bison-binary-cache
-      with:
-        path: |
-          /usr/local/bin/bison
-          /usr/local/lib/liby.a
-          /usr/local/share/bison
-          /usr/local/share/man/man1/bison.1
-        key: ${{ runner.os }}-bison-binary-3.8.2
 
     - name: cache APT packages
       uses: actions/cache@v4
@@ -106,31 +87,7 @@ jobs:
     - name: install native dependencies
       run: |
         sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz clang clang-format clang-tidy libssl-dev
-
-    - name: download Bison source
-      if: steps.bison-source-cache.outputs.cache-hit != 'true'
-      run: |
-        sudo wget http://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-
-    - name: build and install Bison
-      if: steps.bison-binary-cache.outputs.cache-hit != 'true'
-      run: |
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make -j$(nproc)
-        sudo make install
-        cd ..
-        sudo rm -rf bison-3.8.2
-
-    - name: setup Bison symlink
-      run: |
-        if [ -f /usr/bin/bison ]; then
-          sudo mv /usr/bin/bison /usr/bin/bison-prev
-        fi
-        sudo ln -sf /usr/local/bin/bison /usr/bin/bison
-        bison --version
+        sudo apt install -y python3 python3-pip cmake wget clang clang-format clang-tidy libssl-dev
 
     - name: build in release mode & test current codes.
       run: |
@@ -152,24 +109,6 @@ jobs:
     - name: checkout repository codes
       uses: actions/checkout@v4
 
-    - name: cache Bison source
-      uses: actions/cache@v4
-      id: bison-source-cache
-      with:
-        path: bison-3.8.2.tar.gz
-        key: bison-source-3.8.2
-
-    - name: cache Bison binary
-      uses: actions/cache@v4
-      id: bison-binary-cache
-      with:
-        path: |
-          /usr/local/bin/bison
-          /usr/local/lib/liby.a
-          /usr/local/share/bison
-          /usr/local/share/man/man1/bison.1
-        key: ${{ runner.os }}-bison-binary-gcc-3.8.2
-
     - name: cache APT packages
       uses: actions/cache@v4
       with:
@@ -181,33 +120,11 @@ jobs:
     - name: install native dependencies
       run: |
         sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz libssl-dev
+        sudo apt install -y python3 python3-pip cmake wget libssl-dev
 
-    - name: download Bison source
-      if: steps.bison-source-cache.outputs.cache-hit != 'true'
-      run: |
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-
-    - name: build and install Bison
-      if: steps.bison-binary-cache.outputs.cache-hit != 'true'
-      run: |
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make -j$(nproc)
-        sudo make install
-        cd ..
-        sudo rm -rf bison-3.8.2
-
-    - name: setup bison and remove clang
+    - name: remove clang
       run: |
         which clang++ && sudo mv $(which clang++) /tmp || true
-        
-        if [ -f /usr/bin/bison ]; then
-          sudo mv /usr/bin/bison /usr/bin/bison-prev
-        fi
-        sudo ln -sf /usr/local/bin/bison /usr/bin/bison
-        bison --version
 
     - name: build in release mode & test current codes.
       run: |
@@ -223,24 +140,6 @@ jobs:
     steps:
     - name: checkout repository codes
       uses: actions/checkout@v4
-
-    - name: cache Bison source
-      uses: actions/cache@v4
-      id: bison-source-cache
-      with:
-        path: bison-3.8.2.tar.gz
-        key: bison-source-3.8.2
-
-    - name: cache Bison binary
-      uses: actions/cache@v4
-      id: bison-binary-cache
-      with:
-        path: |
-          /usr/local/bin/bison
-          /usr/local/lib/liby.a
-          /usr/local/share/bison
-          /usr/local/share/man/man1/bison.1
-        key: ${{ runner.os }}-bison-binary-coverage-3.8.2
 
     - name: cache APT packages
       uses: actions/cache@v4
@@ -279,7 +178,7 @@ jobs:
     - name: install native dependencies
       run: |
         sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz clang-format clang-tidy llvm perl libcapture-tiny-perl libdatetime-perl libjson-xs-perl
+        sudo apt install -y python3 python3-pip cmake wget clang-format clang-tidy llvm perl libcapture-tiny-perl libdatetime-perl libjson-xs-perl
 
     - name: download lcov source
       if: steps.lcov-source-cache.outputs.cache-hit != 'true'
@@ -298,27 +197,6 @@ jobs:
     - name: verify lcov version
       run: |
         lcov --version
-
-    - name: download Bison source
-      if: steps.bison-source-cache.outputs.cache-hit != 'true'
-      run: |
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-
-    - name: build and install Bison
-      if: steps.bison-binary-cache.outputs.cache-hit != 'true'
-      run: |
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make -j$(nproc)
-        sudo make install
-        cd ..
-        sudo rm -rf bison-3.8.2
-
-    - name: setup Bison symlink
-      run: |
-        sudo mv /usr/bin/bison /usr/bin/bison-prev
-        sudo ln -sf /usr/local/bin/bison /usr/bin/bison
 
     - name: build for measuring coverage
       run: |
@@ -350,53 +228,18 @@ jobs:
         path: |
           ~/Library/Caches/Homebrew
           /opt/homebrew/Cellar
-        key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}-cmake-wget-bison-flex-graphviz
+        key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}-cmake-wget
         restore-keys: |
           ${{ runner.os }}-brew-
-
-    - name: cache Bison source
-      uses: actions/cache@v4
-      id: bison-source-cache
-      with:
-        path: bison-3.8.2.tar.gz
-        key: bison-source-3.8.2
-
-    - name: cache Bison binary
-      uses: actions/cache@v4
-      id: bison-binary-cache
-      with:
-        path: |
-          /usr/local/bin/bison
-          /usr/local/lib/liby.a
-          /usr/local/share/bison
-          /usr/local/share/man/man1/bison.1
-        key: ${{ runner.os }}-bison-binary-3.8.2
 
     - name: install native dependencies
       run: |
         brew unlink python && brew link --overwrite python
         brew uninstall --force cmake || true
-        brew install cmake wget bison flex graphviz
-
-    - name: download Bison source
-      if: steps.bison-source-cache.outputs.cache-hit != 'true'
-      run: |
-        echo "install bison"
-        sudo wget http://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz # avoid SSL network issue
-
-    - name: build and install Bison
-      if: steps.bison-binary-cache.outputs.cache-hit != 'true'
-      run: |
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make -j$(sysctl -n hw.ncpu)
-        sudo make install
-        cd ..
+        brew install cmake wget graphviz
 
     - name: build in release mode & test current codes.
       run: |
-        export PATH="$PATH:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin"
         export C=clang CXX=clang++ PYTHON=$(which python3)
         $PYTHON ${{github.workspace}}/build/builder.py rel --ignore-tidy
         $PYTHON ${{github.workspace}}/build/builder.py test --ignore-tidy
@@ -432,30 +275,8 @@ jobs:
       run: |
         choco install -y wget unzip 7zip
 
-    - name: cache FlexBison zip
-      uses: actions/cache@v4
-      with:
-        path: ${{ github.workspace }}\flex_bison\flex_bison.zip
-        key: ${{ runner.os }}-flexbison-2.5.25
-
-    - name: download FlexBison zip if not cached
-      run: |
-        if (-Not (Test-Path "${{ github.workspace }}\flex_bison\flex_bison.zip")) {
-          New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\flex_bison"
-          Invoke-WebRequest -Uri "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip" -OutFile "${{ github.workspace }}\flex_bison\flex_bison.zip"
-        }
-      shell: pwsh
-
-    - name: unzip FlexBison
-      run: |
-        cd flex_bison
-        unzip flex_bison.zip
-        ren win_flex.exe flex.exe
-        ren win_bison.exe bison.exe
-
     - name: build in release mode
       run: |
-        $env:PATH = "$env:PATH;${{github.workspace}}\flex_bison"
         python ${{github.workspace}}\build\builder.py rel
 
     - name: upload output files.
